DOC: doc update
stfc/openstack-query-library pull request #6
Opened 2024-12-11 13:34 UTC by anish-mudaraddi

updating docs - remove mention of enums in user-docs to favor strings  
adding extra string aliases for presets

2024-12-11 14:52 UTC, gmatthews20 requested changes

2024-12-11 14:52 UTC, gmatthews20 commented on docs/developer_docs/ADDING_NEW_QUERIES.md
> +2. Create a new file under `/enums/` called `<resource>_properties.py`, replace `<resource>` with the name of the openstack resource you want to query
```suggestion
2. Create a new file under `openstackquery/enums/props` called `<resource>_properties.py`, replace `<resource>` with the name of the openstack resource you want to query
```

2024-12-11 14:52 UTC, gmatthews20 commented on docs/developer_docs/OVERVIEW.md
>  Each Query has a corresponding file called `<name_of_resource>_mapping`. The files is located in `/lib/openstack_query/mappings/`
```suggestion
Each Query has a corresponding file called `<name_of_resource>_mapping`. The files is located in `openstackquery/mappings/`
```

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/API.md
Is to_csv still "under development"?

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/API.md
>    - this should be the domain set in the `clouds.yaml` file located in `.config/openstack/clouds.yaml`
```suggestion
  - this should be the domain set in the `clouds.yaml` file located in `.config/openstack/clouds.yaml` (or `/etc/openstack/clouds.yaml`)
```

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/query_docs/HYPERVISORS.md
import line 13 should be `from openstackquery import HypervisorQuery`

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/query_docs/HYPERVISORS.md
> +| "id"   | "hypervisor_id" | One-to-Many | `HypervisorQuery` to `ServerQuery`  | [SERVERS.md](SERVERS.md) |
```suggestion
| "name" |"hypervisor_name"| One-to-Many | `HypervisorQuery` to `ServerQuery`  | [SERVERS.md](SERVERS.md) |
```

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/query_docs/HYPERVISORS.md
> +| `ServerQuery` | "hypervisor_id" | "id"   | Many-to-One | [SERVERS.md](SERVERS.md) |
```suggestion
| `ServerQuery` |"hypervisor_name"| "name" | Many-to-One | [SERVERS.md](SERVERS.md) |
```

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/query_docs/IMAGES.md
Import on line 14 should be `from openstackquery import ImageQuery`

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/query_docs/PROJECTS.md
Import on line 12 should be from `openstackquery import ImageQuery`

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/query_docs/SERVERS.md
Import on line 15 should be `from openstackquery import ServerQuery`

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/query_docs/SERVERS.md
> +| `HypervisorQuery` | `id`   | `"hypervsior_id"` | One-to-Many | [HYPERVISORS.md](HYPERVISORS.md) |
```suggestion
| `HypervisorQuery` | `name` |`"hypervsior_name"`| One-to-Many | [HYPERVISORS.md](HYPERVISORS.md) |
```

2024-12-11 14:52 UTC, gmatthews20 commented on docs/user_docs/query_docs/USERS.md
Import on line 13 should be `from openstackquery import UserQuery`

2024-12-11 16:17 UTC, gmatthews20 approved these changes

2024-12-12 09:08 UTC, khalford requested changes
Rather than adding many comments:

Some paths have a leading forward slash like:
/openstack/enums/...
Other paths do not have a leading forward slash:
openstack/enums/...
Which way is correct?

2024-12-12 09:08 UTC, khalford commented on docs/developer_docs/OVERVIEW.md
> +**NOTE: Deleting or Altering an API method requires approval from maintainers and a good reason since it may break
```suggestion
**NOTE: Deleting or altering an API method requires approval from maintainers and a good reason since it may break
```

2024-12-12 16:11 UTC, anish-mudaraddi commented
@khalford tere's no difference - its just a path - I'll remove the leading / since its more correct

2024-12-13 09:27 UTC, khalford approved these changes

2024-12-13 09:45 UTC, merged